name: CD to heroku

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup for develop main
      Working-directory: ./UserRoleMgtApi
      env: 
	 APP_API_KEY: ${{ secret.APP_API_KEY }}
	 APP_Name: ${{ 'urm01' }}
      run: |
	 docker build -t urm-api .
	 docker tag rum-api registry.heroku.com/$APP_NAME/web
	 docker login --username=_ --password=$APP_API_KEY registry.heroku.com
	 heroku container:push web -a $APP_NAME
	 heroku container:release web -a $APP_NAME
	
