name: CD to heroku

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_pub:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup for develop main
      working-directory: ./UserRoleMgtApi/
      env: 
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        APP_NAME: ${{ 'urm01' }}
      run: |
        docker build -t urm01 .
        docker tag urm01 registry.heroku.com/$APP_NAME/web
        docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com
        heroku container:push web -a $APP_NAME
        heroku container:release web -a $APP_NAME
