name: CI to develop branch

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build_dev:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup for develop branch
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1
    - name: Restore dependencies
      working-directory: ./UserRoleMgtApi
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
